package bd;
// Generated 19 oct. 2022 13:11:23 by Hibernate Tools 6.0.2.Final

/**
 * Correoelectronico generated by hbm2java
 */
public class Correoelectronico implements java.io.Serializable {

	private int idCorreo;
	private Profesor profesor;
	private String direccionCorreo;
	private Integer idx;

	public Correoelectronico() {
	}

	public Correoelectronico(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public Correoelectronico(int idCorreo, Profesor profesor, String direccionCorreo, Integer idx) {
		this.idCorreo = idCorreo;
		this.profesor = profesor;
		this.direccionCorreo = direccionCorreo;
		this.idx = idx;
	}

	public Correoelectronico(int idCorreo, Profesor profesor, String direccionCorreo) {
		super();
		this.idCorreo = idCorreo;
		this.profesor = profesor;
		this.direccionCorreo = direccionCorreo;
	}

	public int getIdCorreo() {
		return this.idCorreo;
	}

	public void setIdCorreo(int idCorreo) {
		this.idCorreo = idCorreo;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getDireccionCorreo() {
		return this.direccionCorreo;
	}

	public void setDireccionCorreo(String direccionCorreo) {
		this.direccionCorreo = direccionCorreo;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	@Override
	public String toString() {
		return "\n" + direccionCorreo;
	}

}
