package bd;
// Generated 19 oct. 2022 13:11:23 by Hibernate Tools 6.0.2.Final

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	private int id;
	private Municipios municipios;
	private Profesor profesor;
	private String calle;
	private Integer numero;
	private String poblacion;
	private String provincia;

	public Direccion() {
	}

	public Direccion(Profesor profesor) {
		this.profesor = profesor;
	}

	public Direccion(Municipios municipios, Profesor profesor, String calle, Integer numero, String poblacion,
			String provincia) {
		this.municipios = municipios;
		this.profesor = profesor;
		this.calle = calle;
		this.numero = numero;
		this.poblacion = poblacion;
		this.provincia = provincia;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String toStringSinProfesor() {
		return calle + ", " + numero + ", " + poblacion + ", " + provincia + " " + municipios;
	}

	@Override
	public String toString() {
		return calle + ", " + numero + ", " + poblacion + ", " + provincia + " " + municipios + " \nProfesor: \n"
				+ profesor.toStringSinDireccion();
	}

}
