package bd;
// Generated 19 oct. 2022 13:11:23 by Hibernate Tools 6.0.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private Integer idMunicipio;
	private String codProvincia;
	private String codMunicipio;
	private String nombreMunicipio;
	private Set direccions = new HashSet(0);

	public Municipios() {
	}

	public Municipios(String codProvincia, String codMunicipio, String nombreMunicipio, Set direccions) {
		this.codProvincia = codProvincia;
		this.codMunicipio = codMunicipio;
		this.nombreMunicipio = nombreMunicipio;
		this.direccions = direccions;
	}

	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public String getCodProvincia() {
		return this.codProvincia;
	}

	public void setCodProvincia(String codProvincia) {
		this.codProvincia = codProvincia;
	}

	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public String getNombreMunicipio() {
		return this.nombreMunicipio;
	}

	public void setNombreMunicipio(String nombreMunicipio) {
		this.nombreMunicipio = nombreMunicipio;
	}

	public Set getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set direccions) {
		this.direccions = direccions;
	}

}
