package bd;
// Generated 19 oct. 2022 13:11:23 by Hibernate Tools 6.0.2.Final

/**
 * Profesormodulo generated by hbm2java
 */
public class Profesormodulo implements java.io.Serializable {

	private ProfesormoduloId id;
	private Profesor profesor;
	private Modulo modulo;
	private Integer idx;

	public Profesormodulo() {
	}

	public Profesormodulo(ProfesormoduloId id, Profesor profesor, Modulo modulo) {
		this.id = id;
		this.profesor = profesor;
		this.modulo = modulo;
	}

	public Profesormodulo(ProfesormoduloId id, Profesor profesor, Modulo modulo, Integer idx) {
		this.id = id;
		this.profesor = profesor;
		this.modulo = modulo;
		this.idx = idx;
	}

	public ProfesormoduloId getId() {
		return this.id;
	}

	public void setId(ProfesormoduloId id) {
		this.id = id;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

}
